name: Build and Lint Products Project

on:
  push:
    paths:
      - "products/**"
  pull_request:
    paths:
      - "products/**"

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn install

  lint-and-build:
    needs: install-dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Lint and Build Products
        run: |
          yarn workspace products lint
          yarn workspace products build

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: shared-artifacts
          path: products/dist
